window.MEDPEN_TOOLS = [
  // recon
  {id:"nmap",cat:"scan",ph:["scan","recon"],inst:true,desc:"포트·서비스·OS 탐지의 사실상 표준. NSE 스크립트로 취약점·프로토콜 핑거프린팅까지.",cmd:"nmap -sV -sC -p- --open 10.0.0.0/24",samd:"네트워크 연결 SaMD/SiMD의 노출 서비스와 의료 프로토콜 포트(DICOM 104, HL7 2575) 식별.",tags:["ip"]},
  {id:"masscan",cat:"scan",ph:["scan"],inst:true,desc:"대규모 대역을 초고속으로 스캔하는 비동기 포트 스캐너.",cmd:"masscan 10.0.0.0/16 -p1-65535 --rate 1000",samd:"병원 네트워크 등 넓은 세그먼트에서 의료기기 자산을 신속 발견.",tags:["ip"]},
  {id:"nuclei",cat:"scan",ph:["scan","web"],inst:true,desc:"템플릿 기반 취약점 스캐너. CVE·설정오류·노출을 YAML 규칙으로 탐지.",cmd:"nuclei -u https://app.target -severity high,critical",samd:"SaMD 웹/클라우드 자산의 알려진 취약점을 빠르게 트리아지.",tags:["ip","web"]},
  {id:"openvas",cat:"scan",ph:["scan"],inst:true,desc:"종합 취약점 평가 스캐너(Greenbone). 인증 스캔·정책 점검.",cmd:"gvm-start   # 웹 UI 9392",samd:"사후시장 SaMD 인프라의 주기적 취약점 베이스라인.",tags:["ip"]},
  {id:"theharvester",cat:"recon",ph:["recon"],inst:true,desc:"이메일·서브도메인·호스트 등 공개 출처 정보 수집(OSINT).",cmd:"theHarvester -d vendor.com -b all",samd:"제조사·클라우드 공급자 노출 자산과 담당자 식별.",tags:[]},
  {id:"amass",cat:"recon",ph:["recon"],inst:true,desc:"심층 자산·서브도메인 매핑. 외부 공격표면 그래프화.",cmd:"amass enum -d vendor.com",samd:"SaMD 클라우드·API 엔드포인트의 외부 공격표면 전수화.",tags:[]},
  {id:"spiderfoot",cat:"recon",ph:["recon"],inst:true,desc:"자동화 OSINT 수집·상관분석 플랫폼.",cmd:"spiderfoot -l 127.0.0.1:5001",samd:"벤더 생태계(노출 자격증명, 서드파티) 상관 분석.",tags:[]},
  {id:"recon-ng",cat:"recon",ph:["recon"],inst:true,desc:"모듈형 웹 정찰 프레임워크.",cmd:"recon-ng -w samd",samd:"구조화된 정찰 워크플로로 자산 데이터 집계.",tags:[]},
  {id:"dnsrecon",cat:"recon",ph:["recon"],inst:true,desc:"DNS 열거·영역전송·레코드 수집.",cmd:"dnsrecon -d vendor.com -a",samd:"API·업데이트 서버 등 숨은 호스트 발견.",tags:[]},
  {id:"dnsenum",cat:"recon",ph:["recon"],inst:true,desc:"DNS 정보·서브도메인 브루트포스 수집.",cmd:"dnsenum vendor.com",samd:"SaMD 백엔드 명명 규칙에서 추가 자산 유추.",tags:[]},
  {id:"fierce",cat:"recon",ph:["recon"],inst:true,desc:"DNS 정찰로 인접 네임스페이스 탐색.",cmd:"fierce --domain vendor.com",samd:"스테이징·개발 환경 등 비공개 엔드포인트 식별.",tags:[]},
  {id:"whatweb",cat:"recon",ph:["recon","web"],inst:true,desc:"웹 기술 스택·프레임워크·버전 핑거프린팅.",cmd:"whatweb -a 3 https://app.target",samd:"SaMD 프런트엔드/서버 구성요소와 버전 식별.",tags:["web"]},
  {id:"wafw00f",cat:"recon",ph:["recon","web"],inst:true,desc:"웹 방화벽(WAF) 존재·종류 탐지.",cmd:"wafw00f https://app.target",samd:"테스트 경로상의 보호 계층 파악으로 절차 조정.",tags:["web"]},
  // traffic / protocol
  {id:"wireshark",cat:"traffic",ph:["traffic"],inst:true,desc:"GUI 패킷 분석기. 프로토콜 디섹터로 심층 분석.",cmd:"wireshark &   # dicom/hl7 필터",samd:"DICOM·HL7·전용 프로토콜의 평문 전송·인증 결함 관찰.",tags:["ip","dicom","hl7","mqtt"]},
  {id:"tshark",cat:"traffic",ph:["traffic"],inst:true,desc:"Wireshark의 CLI. 자동화·대용량 캡처에 적합.",cmd:"tshark -i eth0 -Y dicom -w cap.pcap",samd:"스크립트로 의료 프로토콜 세션을 추출·검증.",tags:["ip","dicom","hl7"]},
  {id:"tcpdump",cat:"traffic",ph:["traffic"],inst:true,desc:"경량 패킷 캡처 도구. 장비·게이트웨이에서 사용.",cmd:"tcpdump -i eth0 port 104 -w dicom.pcap",samd:"대역폭이 제한된 임베디드 환경에서 트래픽 확보.",tags:["ip","dicom"]},
  {id:"scapy",cat:"traffic",ph:["traffic","exploit","wireless"],inst:true,desc:"패킷 제작·조작·전송 파이썬 라이브러리. 프로토콜 퍼징 핵심.",cmd:"from scapy.all import *",samd:"전용/비공개 의료 프로토콜의 커스텀 퍼징·재전송 테스트.",tags:["ip","rf","prop","dicom"]},
  {id:"ettercap",cat:"traffic",ph:["traffic","exploit"],inst:true,desc:"중간자(MITM) 공격·세션 가로채기 스위트 (dsniff/arpspoof 포함).",cmd:"arpspoof -t <dev> <gw>",samd:"격리 벤치에서 평문 프로토콜의 변조·가로채기 영향 입증.",tags:["ip"]},
  {id:"mitmproxy",cat:"web",ph:["web","traffic"],inst:true,desc:"HTTP/S 가로채기 프록시. 스크립팅으로 트래픽 변조.",cmd:"mitmproxy --mode transparent",samd:"모바일 SaMD의 API 호출 가로채기·인증서 핀닝 검증.",tags:["web","mobile"]},
  {id:"responder",cat:"traffic",ph:["traffic","cred"],inst:true,desc:"LLMNR/NBT-NS/mDNS 포이즈닝으로 자격증명 수집.",cmd:"responder -I eth0",samd:"병원 내부망 SaMD 서버의 인증 흐름 약점 검증(격리망).",tags:["ip"]},
  {id:"snmpwalk",cat:"traffic",ph:["traffic","recon"],inst:true,desc:"SNMP로 장비 설정·자산 정보 열거.",cmd:"snmpwalk -v2c -c public <dev>",samd:"관리 인터페이스가 열린 의료기기 구성 노출 확인.",tags:["ip"]},
  {id:"enum4linux",cat:"traffic",ph:["traffic","recon"],inst:true,desc:"SMB/Windows 공유·사용자·정책 열거.",cmd:"enum4linux -a <host>",samd:"Windows 기반 PACS/워크스테이션의 공유·계정 노출.",tags:["ip"]},
  {id:"smbclient",cat:"traffic",ph:["traffic"],inst:true,desc:"SMB 공유 접근·파일 전송 클라이언트.",cmd:"smbclient -L //<host> -N",samd:"영상·리포트 공유의 익명 접근 가능성 확인.",tags:["ip"]},
  // web
  {id:"burpsuite",cat:"web",ph:["web"],inst:true,desc:"웹/API 테스트 통합 플랫폼. 프록시·스캐너·리피터·인트루더.",cmd:"burpsuite &",samd:"SaMD 웹/API의 인증·권한·입력검증 결함을 체계적으로 평가.",tags:["web","mobile"]},
  {id:"sqlmap",cat:"web",ph:["web","exploit"],inst:true,desc:"SQL 인젝션 자동 탐지·추출.",cmd:"sqlmap -u 'https://app/api?id=1' --batch",samd:"PHI 저장 백엔드에 대한 인젝션으로 데이터 노출 위험 입증.",tags:["web","phi"]},
  {id:"nikto",cat:"web",ph:["web","scan"],inst:true,desc:"웹 서버 설정오류·위험 파일 스캐너.",cmd:"nikto -h https://app.target",samd:"SaMD 서버의 노출 관리 페이지·구버전 식별.",tags:["web"]},
  {id:"ffuf",cat:"web",ph:["web"],inst:true,desc:"초고속 웹 퍼저. 디렉터리·파라미터·vhost 탐색.",cmd:"ffuf -u https://app/FUZZ -w wordlist",samd:"숨은 API 엔드포인트·관리 경로 발견.",tags:["web"]},
  {id:"gobuster",cat:"web",ph:["web"],inst:true,desc:"디렉터리·DNS·vhost 브루트포스.",cmd:"gobuster dir -u https://app -w list",samd:"문서화되지 않은 SaMD 리소스 열거.",tags:["web"]},
  {id:"dirb",cat:"web",ph:["web"],inst:true,desc:"웹 콘텐츠 디렉터리 스캐너.",cmd:"dirb https://app.target",samd:"경량 디렉터리 탐색 대안.",tags:["web"]},
  {id:"wpscan",cat:"web",ph:["web"],inst:true,desc:"WordPress 취약점·플러그인·사용자 스캐너.",cmd:"wpscan --url https://portal.target",samd:"환자 포털 등 CMS 기반 SaMD 자산 평가.",tags:["web"]},
  {id:"sslscan",cat:"web",ph:["web","cred"],inst:true,desc:"TLS 구성·암호군·인증서 점검.",cmd:"sslscan app.target:443",samd:"PHI 전송 구간의 약한 TLS·만료 인증서 식별.",tags:["web","phi","ip"]},
  {id:"sslyze",cat:"web",ph:["web","cred"],inst:true,desc:"정밀 TLS 분석기. 취약점·설정 자동 평가.",cmd:"sslyze app.target:443",samd:"전송 암호화 준수(FDA·HIPAA) 근거 자료 생성.",tags:["web","phi","ip"]},
  // wireless / BLE
  {id:"aircrack-ng",cat:"wireless",ph:["wireless"],inst:true,desc:"Wi-Fi 모니터링·캡처·WPA 핸드셰이크 크래킹 스위트.",cmd:"airodump-ng wlan0mon",samd:"Wi-Fi 연결 의료기기의 무선 보안·분리(segmentation) 검증.",tags:["ip"]},
  {id:"kismet",cat:"wireless",ph:["wireless","recon"],inst:true,desc:"무선 탐지·스니핑·디바이스 트래킹(Wi-Fi/BT/SDR).",cmd:"kismet -c wlan0mon",samd:"테스트 공간 내 미등록 무선 의료기기 발견.",tags:["ble","rf"]},
  {id:"reaver",cat:"wireless",ph:["wireless"],inst:true,desc:"WPS 핀 브루트포스로 Wi-Fi 키 복구.",cmd:"reaver -i wlan0mon -b <bssid>",samd:"WPS가 켜진 기기 게이트웨이의 약점 입증.",tags:["ip"]},
  {id:"bluetoothctl",cat:"wireless",ph:["wireless","recon"],inst:true,desc:"BlueZ 제어 CLI. BLE 장치 스캔·페어링·연결.",cmd:"bluetoothctl scan on",samd:"BLE 웨어러블/이식형의 광고·페어링 보안 관찰.",tags:["ble"]},
  {id:"gatttool",cat:"wireless",ph:["wireless","exploit"],inst:true,desc:"BLE GATT 서비스·특성 열거 및 읽기/쓰기.",cmd:"gatttool -b <MAC> -I",samd:"BLE 기기의 인증 없는 특성 쓰기(명령 주입) 검증.",tags:["ble"]},
  {id:"hcitool",cat:"wireless",ph:["wireless","recon"],inst:true,desc:"저수준 Bluetooth 조회·장치 탐색.",cmd:"hcitool lescan",samd:"BLE 기기 식별·MAC 수집(프라이버시·랜덤화 점검).",tags:["ble"]},
  {id:"spooftooph",cat:"wireless",ph:["wireless","exploit"],inst:true,desc:"Bluetooth 장치 정보 스푸핑.",cmd:"spooftooph -i hci0 -a <MAC>",samd:"BLE 신뢰·페어링 모델의 위조 내성 평가.",tags:["ble"]},
  // firmware / embedded
  {id:"binwalk",cat:"firmware",ph:["firmware"],inst:true,desc:"펌웨어 이미지 분석·파일시스템 추출·엔트로피 분석.",cmd:"binwalk -eM firmware.bin",samd:"SiMD 펌웨어에서 파일시스템·하드코딩 비밀 추출.",tags:["usb","prop"]},
  {id:"radare2",cat:"firmware",ph:["firmware","exploit"],inst:true,desc:"역공학 프레임워크. 디스어셈블·디버그·패치.",cmd:"r2 -A firmware.elf",samd:"펌웨어 바이너리의 로직·인증 우회 경로 분석.",tags:["usb","prop"]},
  {id:"sasquatch",cat:"firmware",ph:["firmware"],inst:true,desc:"변형 SquashFS 추출 유틸(binwalk 보조).",cmd:"sasquatch rootfs.squashfs",samd:"비표준 압축 펌웨어 루트FS 복원.",tags:["usb"]},
  {id:"flashrom",cat:"firmware",ph:["firmware"],inst:true,desc:"SPI/플래시 칩 읽기·쓰기(하드웨어 프로그래머 연동).",cmd:"flashrom -p <prog> -r dump.bin",samd:"물리 접근 시 SiMD 플래시에서 펌웨어 직접 덤프.",tags:["usb"]},
  {id:"objdump",cat:"firmware",ph:["firmware"],inst:true,desc:"바이너리 디스어셈블·섹션 분석(binutils).",cmd:"objdump -d firmware.elf",samd:"임베디드 바이너리의 함수·심볼 신속 검토.",tags:["usb"]},
  {id:"strings",cat:"firmware",ph:["firmware","recon"],inst:true,desc:"바이너리 내 출력가능 문자열 추출.",cmd:"strings -n 8 firmware.bin",samd:"펌웨어의 자격증명·엔드포인트·디버그 문자열 발견.",tags:["usb","prop"]},
  // exploitation
  {id:"metasploit",cat:"exploit",ph:["exploit"],inst:true,desc:"익스플로잇·페이로드·포스트 모듈 프레임워크(msfconsole).",cmd:"msfconsole -q",samd:"확인된 취약점의 영향(안전 영향 포함)을 통제된 PoC로 입증.",tags:["ip","web"]},
  // credential / crypto
  {id:"hydra",cat:"cred",ph:["cred"],inst:true,desc:"네트워크 로그인 브루트포스(SSH/HTTP/RDP 등).",cmd:"hydra -L u.txt -P p.txt ssh://<host>",samd:"관리 인터페이스의 약한·기본 자격증명 검증.",tags:["ip","web"]},
  {id:"john",cat:"cred",ph:["cred"],inst:true,desc:"John the Ripper. 해시 크래킹·규칙 기반 공격.",cmd:"john --wordlist=rock.txt hashes",samd:"펌웨어/DB에서 추출한 해시의 강도 평가.",tags:[]},
  {id:"hashcat",cat:"cred",ph:["cred"],inst:true,desc:"GPU 가속 해시 크래킹.",cmd:"hashcat -m 0 -a 0 hashes rock.txt",samd:"대량 해시·강한 알고리즘의 현실적 크래킹 비용 산정.",tags:[]},
  // --- recommended (not confirmed on this host) ---
  {id:"dcmtk",cat:"traffic",ph:["traffic","exploit"],inst:true,desc:"DICOM 툴킷(storescu/findscu/echoscu). DICOM 노드와 직접 통신.",cmd:"echoscu <host> 104   # C-ECHO 연결 확인",samd:"DICOM 서비스의 인증 부재·C-STORE 남용·정보 열거 테스트.",tags:["dicom","ip"]},
  {id:"mosquitto",cat:"traffic",ph:["traffic","exploit"],inst:true,desc:"MQTT 브로커·클라이언트(pub/sub). IoT 메시징 테스트.",cmd:"mosquitto_sub -h <broker> -t '#' -v",samd:"원격 모니터링 SiMD의 MQTT 토픽 무단 구독·발행 검증.",tags:["mqtt","ip"]},
  {id:"frida",cat:"exploit",ph:["exploit","web"],inst:true,desc:"동적 계측 툴킷. 런타임 후킹·인증서 핀닝 우회.",cmd:"frida-ps -U   # USB 기기 프로세스 목록",samd:"모바일 SaMD의 핀닝 우회·런타임 로직 분석.",tags:["mobile"]},
  {id:"apktool",cat:"exploit",ph:["firmware","exploit"],inst:true,desc:"안드로이드 APK 디컴파일·리빌드.",cmd:"apktool d app.apk -o out/",samd:"모바일 SaMD의 리소스·스몰리 코드·비밀 정적 분석.",tags:["mobile"]},
  {id:"jadx",cat:"firmware",ph:["firmware"],inst:true,desc:"Dalvik 바이트코드를 Java로 디컴파일.",cmd:"jadx -d out/ app.apk",samd:"모바일 SaMD 앱 로직·하드코딩 키 검토.",tags:["mobile"]},
  {id:"ghidra",cat:"firmware",ph:["firmware","exploit"],inst:true,desc:"NSA 역공학 스위트. 멀티아키 디컴파일.",cmd:"ghidra &   # GUI 프로젝트 생성",samd:"SiMD 펌웨어의 심층 역공학·취약점 식별.",tags:["usb","prop"]},
  {id:"can-utils",cat:"traffic",ph:["traffic","exploit"],inst:true,desc:"CAN 버스 송수신·덤프(candump/cansend).",cmd:"candump can0   # 버스 트래픽 관찰",samd:"CAN 기반 의료 플랫폼의 버스 메시지 관찰·주입.",tags:["prop","usb"]},
  {id:"volatility3",cat:"exploit",ph:["exploit","report"],inst:true,desc:"메모리 포렌식 프레임워크(vol).",cmd:"vol -f dump.raw windows.info",samd:"사후시장 사고 대응·메모리 내 PHI 잔존 확인.",tags:["phi"]},
  {id:"objection",cat:"exploit",ph:["exploit"],inst:true,desc:"Frida 기반 런타임 모바일 탐색·핀닝 우회 자동화.",cmd:"objection -g <pkg> explore",samd:"모바일 SaMD의 핀닝 우회·로컬 저장소·메서드 후킹 신속 점검.",tags:["mobile"]},
  // ===== metapackage: SDR / RF (하드웨어) =====
  {id:"gnuradio",cat:"hardware",ph:["wireless","traffic"],inst:true,chk:"gnuradio-config-info",desc:"SDR 신호처리 프레임워크. 전용 무선 프로토콜의 복조·디코딩 플로우 구성.",cmd:"gnuradio-companion &",samd:"전용 RF로 통신하는 SiMD(텔레메트리·이식형)의 변조 방식 역설계.",tags:["rf","prop"]},
  {id:"gqrx",cat:"hardware",ph:["wireless","recon"],inst:true,chk:"gqrx",desc:"SDR 수신·스펙트럼 분석 GUI.",cmd:"gqrx &",samd:"의료기기의 RF 방출 대역·채널 식별(정찰).",tags:["rf"]},
  {id:"hackrf",cat:"hardware",ph:["wireless"],inst:true,chk:"hackrf_info",desc:"1MHz–6GHz SDR 송수신 하드웨어 도구모음.",cmd:"hackrf_info   # 기기 연결 확인",samd:"격리 벤치에서 전용 RF 신호 캡처·재전송(replay) 내성 검증.",tags:["rf","prop"]},
  {id:"multimon-ng",cat:"hardware",ph:["wireless","traffic"],inst:true,chk:"multimon-ng",desc:"POCSAG·FLEX 등 디지털 모드 디코더.",cmd:"multimon-ng -a POCSAG1200 -",samd:"병원 호출(pager) 등 평문 텔레메트리의 정보 노출 확인.",tags:["rf"]},
  {id:"inspectrum",cat:"hardware",ph:["wireless"],inst:true,chk:"inspectrum",desc:"캡처된 신호의 시각적 분석·심볼 추출.",cmd:"inspectrum capture.cf32",samd:"전용 RF의 패킷 구조·타이밍 역설계.",tags:["rf","prop"]},
  {id:"rfcat",cat:"hardware",ph:["wireless","exploit"],inst:true,chk:"rfcat",desc:"서브-GHz(ISM) RF 송수신 제어(TI 칩셋).",cmd:"rfcat -r",samd:"ISM 대역 전용 프로토콜의 명령 주입·재전송 테스트.",tags:["rf","prop"]},
  // ===== metapackage: RFID =====
  {id:"proxmark3",cat:"hardware",ph:["wireless","exploit"],inst:true,chk:"proxmark3",desc:"RFID/NFC 분석·복제·에뮬레이션 플랫폼.",cmd:"proxmark3 /dev/ttyACM0",samd:"RFID 기반 접근제어·이식형 식별 태그의 복제·변조 내성 검증.",tags:["rf","prop"]},
  // ===== metapackage: hardware (JTAG/UART/emulation/RE) =====
  {id:"openocd",cat:"hardware",ph:["firmware"],inst:true,chk:"openocd",desc:"JTAG/SWD 온칩 디버깅·플래시 접근.",cmd:"openocd -f board.cfg",samd:"SiMD의 디버그 포트를 통한 펌웨어 덤프·메모리 접근(보호 여부 검증).",tags:["usb"]},
  {id:"minicom",cat:"hardware",ph:["firmware","traffic"],inst:true,chk:"minicom",desc:"시리얼 터미널. UART 콘솔 접근.",cmd:"minicom -D /dev/ttyUSB0 -b 115200",samd:"의료기기 UART 콘솔의 인증 없는 셸·부트로그 노출 확인.",tags:["usb"]},
  {id:"qemu-user",cat:"hardware",ph:["firmware","exploit"],inst:true,chk:"qemu-arm",desc:"크로스아키 사용자모드 에뮬레이션(ARM/MIPS 등).",cmd:"qemu-arm ./fw-binary",samd:"추출한 SiMD 펌웨어 바이너리를 격리 환경에서 안전하게 실행·분석.",tags:["usb","prop"]},
  {id:"cutter",cat:"firmware",ph:["firmware","exploit"],inst:true,chk:"cutter",desc:"Rizin 기반 역공학 GUI(rz-ghidra 디컴파일러 포함).",cmd:"cutter firmware.elf",samd:"Ghidra 대안으로 펌웨어 디컴파일·그래프 분석.",tags:["usb","prop"]},
  // ===== metapackage: bluetooth (BLE) =====
  {id:"ubertooth",cat:"wireless",ph:["wireless","traffic"],inst:true,chk:"ubertooth-util",desc:"BLE 패킷 스니핑 하드웨어 도구모음.",cmd:"ubertooth-util -v",samd:"앱-기기 간 BLE 트래픽 캡처로 평문·약한 페어링 식별.",tags:["ble"]},
  {id:"crackle",cat:"wireless",ph:["wireless","cred"],inst:true,chk:"crackle",desc:"BLE 레거시 페어링(LE Legacy) 암호 크랙.",cmd:"crackle -i ble.pcap",samd:"BLE 웨어러블/이식형의 약한 페어링으로 인한 트래픽 복호화 입증.",tags:["ble"]},
  {id:"btscanner",cat:"wireless",ph:["wireless","recon"],inst:true,chk:"btscanner",desc:"Bluetooth 장치 탐색·정보 수집.",cmd:"btscanner",samd:"테스트 공간의 BLE 의료기기 식별·정보 노출 점검.",tags:["ble"]},
  // ===== metapackage: reverse-engineering (mobile) =====
  {id:"dex2jar",cat:"firmware",ph:["firmware"],inst:true,chk:"d2j-dex2jar",desc:"Android dex를 jar로 변환(정적 분석용).",cmd:"d2j-dex2jar app.apk",samd:"모바일 SaMD를 jd-gui 등으로 Java 수준 검토하기 위한 전처리.",tags:["mobile"]},
  {id:"jd-gui",cat:"firmware",ph:["firmware"],inst:true,chk:"jd-gui",desc:"Java 바이트코드 디컴파일 GUI.",cmd:"jd-gui app-dex2jar.jar",samd:"모바일 SaMD 로직·하드코딩 비밀의 가독성 높은 검토.",tags:["mobile"]},
  // ===== SBOM / 공급망 (FDA 제출 요소) =====
  {id:"syft",cat:"sbom",ph:["report"],inst:false,chk:"syft",desc:"SBOM 생성기. 파일시스템·이미지에서 SPDX/CycloneDX SBOM 산출.",cmd:"syft dir:./firmware -o cyclonedx-json",samd:"FDA 요구 기계판독 SBOM 생성 — 구성요소·버전 목록화.",tags:["phi"]},
  {id:"trivy",cat:"sbom",ph:["report"],inst:false,chk:"trivy",desc:"SBOM 생성 + 알려진 취약점(CVE) 스캔. 파일시스템·이미지·SBOM 대상.",cmd:"trivy fs --format cyclonedx -o sbom.json ./app",samd:"SBOM 구성요소의 알려진 취약점 대조(사후시장 관리 근거).",tags:["phi"]},
  {id:"cyclonedx",cat:"sbom",ph:["report"],inst:false,chk:"cyclonedx-py",desc:"CycloneDX SBOM 생성(Python 의존성).",cmd:"cyclonedx-py requirements -i requirements.txt",samd:"Python 기반 SaMD의 표준 포맷 SBOM 산출.",tags:["phi"]},
  {id:"pip-audit",cat:"sbom",ph:["report"],inst:false,chk:"pip-audit",desc:"Python 의존성의 알려진 취약점 감사.",cmd:"pip-audit -r requirements.txt",samd:"SaMD 백엔드 의존성의 취약 패키지 식별.",tags:["phi"]}
];

/* 각 툴의 상세: ov=개요, tc=[{t:제목,s:절차}] 테스트 케이스, cs=[사례], rf=[[라벨,URL]] 참고 */
window.MEDPEN_DETAIL = {
  nmap:{ov:"포트·서비스·OS 핑거프린팅의 사실상 표준. NSE 스크립트로 취약점·프로토콜 탐지까지 확장된다.",tc:[{t:"전체 포트·버전 식별",s:"nmap -sV -sC -p- --open <target> 로 열린 포트·서비스·기본 NSE 스크립트 실행"},{t:"의료 프로토콜 포트 탐지",s:"nmap -p 104,2575,11112,1883 <target> 로 DICOM(104)·HL7(2575)·MQTT(1883) 노출 확인"},{t:"NSE 취약점 스캔",s:"nmap --script vuln <target> 로 알려진 CVE·설정 오류 점검"}],cs:["병원 네트워크 세그먼트에서 관리되지 않는 의료기기(섀도 IT) 자산 식별","DICOM 노드의 비인증 서비스 노출 확인"],rf:[["Nmap Reference Guide","https://nmap.org/book/man.html"]]},
  masscan:{ov:"인터넷 규모의 대역을 초고속으로 훑는 비동기 포트 스캐너.",tc:[{t:"대역 신속 스캔",s:"masscan <CIDR> -p1-65535 --rate 1000 으로 넓은 세그먼트의 열린 포트 수집"},{t:"의료 포트 집중 스캔",s:"masscan <CIDR> -p104,2575,1883,502 --rate 500 로 의료·산업 프로토콜 포트만 신속 탐색"}],cs:["대형 병원 VLAN 전수조사로 자산 인벤토리 초안 작성"],rf:[["masscan","https://github.com/robertdavidgraham/masscan"]]},
  nuclei:{ov:"YAML 템플릿 기반 취약점 스캐너. CVE·설정 오류·노출을 빠르게 트리아지한다.",tc:[{t:"고위험 취약점 스캔",s:"nuclei -u https://app -severity high,critical 로 심각 항목 우선 탐지"},{t:"기술스택 맞춤 템플릿",s:"nuclei -u https://app -tags cve,exposure,misconfig 로 범주 지정 스캔"}],cs:["SaMD 클라우드 포털의 알려진 라이브러리 취약점 신속 선별"],rf:[["Nuclei Docs","https://docs.projectdiscovery.io/tools/nuclei"]]},
  openvas:{ov:"Greenbone 기반 종합 취약점 평가 스캐너. 인증 스캔·정책 점검을 지원한다.",tc:[{t:"인증 스캔",s:"자격증명 등록 후 전체 스캔으로 패치 누락·설정 취약점 평가"},{t:"주기적 베이스라인",s:"사후시장 SaMD 인프라에 대해 정기 스캔으로 취약점 추세 관리"}],cs:["규제 대응용 주기적 취약점 리포트 생성"],rf:[["Greenbone Docs","https://greenbone.github.io/docs/"]]},
  theharvester:{ov:"공개 출처에서 이메일·서브도메인·호스트를 수집하는 OSINT 도구.",tc:[{t:"도메인 자산 수집",s:"theHarvester -d <vendor> -b all 로 서브도메인·이메일·호스트 집계"}],cs:["제조사·클라우드 공급자의 외부 노출 자산과 담당자 식별"],rf:[["theHarvester","https://github.com/laramies/theHarvester"]]},
  amass:{ov:"OWASP Amass. 심층 자산·서브도메인 매핑으로 외부 공격표면을 그래프화한다.",tc:[{t:"서브도메인 열거",s:"amass enum -d <vendor> 로 수동·능동 수집 통합"},{t:"공격표면 시각화",s:"amass viz 로 수집 자산 관계 그래프화"}],cs:["SaMD 클라우드·API 엔드포인트의 외부 공격표면 전수화"],rf:[["OWASP Amass","https://github.com/owasp-amass/amass"]]},
  spiderfoot:{ov:"자동화 OSINT 수집·상관분석 플랫폼.",tc:[{t:"자동 수집 스캔",s:"웹 UI(spiderfoot -l 127.0.0.1:5001)에서 대상 지정 후 모듈 전수 실행"}],cs:["벤더 생태계의 노출 자격증명·서드파티 위험 상관 분석"],rf:[["SpiderFoot","https://github.com/smicallef/spiderfoot"]]},
  "recon-ng":{ov:"모듈형 웹 정찰 프레임워크.",tc:[{t:"워크스페이스 정찰",s:"recon-ng -w <name> 으로 모듈을 조합해 자산 데이터 집계"}],cs:["구조화된 정찰 워크플로로 반복 가능한 자산 수집"],rf:[["recon-ng","https://github.com/lanmaster53/recon-ng"]]},
  dnsrecon:{ov:"DNS 열거·영역전송·레코드 수집 도구.",tc:[{t:"종합 DNS 열거",s:"dnsrecon -d <vendor> -a 로 레코드·영역전송 시도"}],cs:["API·업데이트 서버 등 숨은 호스트 발견"],rf:[["dnsrecon","https://github.com/darkoperator/dnsrecon"]]},
  dnsenum:{ov:"DNS 정보·서브도메인 브루트포스 수집.",tc:[{t:"서브도메인 브루트포스",s:"dnsenum <vendor> 로 워드리스트 기반 서브도메인 추정"}],cs:["SaMD 백엔드 명명 규칙에서 추가 자산 유추"],rf:[["dnsenum","https://github.com/fwaeytens/dnsenum"]]},
  fierce:{ov:"인접 네임스페이스를 탐색하는 DNS 정찰 도구.",tc:[{t:"네임스페이스 스캔",s:"fierce --domain <vendor> 로 인접 호스트·스테이징 환경 탐색"}],cs:["스테이징·개발 환경 등 비공개 엔드포인트 식별"],rf:[["fierce","https://github.com/mschwager/fierce"]]},
  whatweb:{ov:"웹 기술 스택·프레임워크·버전을 핑거프린팅한다.",tc:[{t:"심층 핑거프린팅",s:"whatweb -a 3 https://app 로 서버·프레임워크·플러그인 버전 식별"}],cs:["SaMD 프런트엔드/서버 구성요소와 구버전 식별"],rf:[["WhatWeb","https://github.com/urbanadventurer/WhatWeb"]]},
  wafw00f:{ov:"웹 방화벽(WAF) 존재·종류를 탐지한다.",tc:[{t:"WAF 탐지",s:"wafw00f https://app 로 보호 계층 유무·제품 식별"}],cs:["테스트 경로상의 보호 계층을 파악해 절차·우회 전략 조정"],rf:[["wafw00f","https://github.com/EnableSecurity/wafw00f"]]},
  wireshark:{ov:"GUI 패킷 분석기. 풍부한 프로토콜 디섹터로 심층 분석이 가능하다.",tc:[{t:"DICOM 세션 관찰",s:"캡처 후 필터 dicom 으로 C-STORE/C-FIND 평문·인증 결함 확인"},{t:"HL7 메시지 추출",s:"필터 hl7 또는 포트 2575 로 환자정보 평문 전송 여부 점검"}],cs:["의료 프로토콜의 평문 전송·약한 인증을 시각적으로 입증"],rf:[["Wireshark Docs","https://www.wireshark.org/docs/"]]},
  tshark:{ov:"Wireshark의 CLI. 자동화·대용량 캡처 처리에 적합하다.",tc:[{t:"스크립트 기반 추출",s:"tshark -i <if> -Y dicom -w cap.pcap 로 특정 프로토콜만 캡처"}],cs:["의료 프로토콜 세션을 스크립트로 추출·검증"],rf:[["tshark","https://www.wireshark.org/docs/man-pages/tshark.html"]]},
  tcpdump:{ov:"경량 패킷 캡처 도구. 게이트웨이·임베디드 환경에서 쓰인다.",tc:[{t:"포트별 캡처",s:"tcpdump -i <if> port 104 -w dicom.pcap 로 대상 트래픽 확보"}],cs:["대역폭·자원이 제한된 임베디드 환경에서 트래픽 수집"],rf:[["tcpdump","https://www.tcpdump.org/manpages/tcpdump.1.html"]]},
  scapy:{ov:"패킷 제작·조작·전송 파이썬 라이브러리. 프로토콜 퍼징의 핵심이다.",tc:[{t:"커스텀 패킷 제작",s:"Scapy로 전용 프로토콜 필드를 조작해 재전송·변조 응답 관찰"},{t:"프로토콜 퍼징",s:"필드를 무작위화하며 전송해 파서 예외·크래시 유발 여부 확인"}],cs:["전용/비공개 의료 프로토콜의 커스텀 퍼징·재전송 테스트"],rf:[["Scapy Docs","https://scapy.readthedocs.io/"]]},
  ettercap:{ov:"중간자(MITM)·세션 가로채기 스위트(dsniff/arpspoof 포함).",tc:[{t:"ARP 스푸핑 MITM",s:"격리 벤치에서 arpspoof 로 경로를 가로채 평문 프로토콜 변조 영향 입증"}],cs:["평문 의료 프로토콜의 가로채기·변조 위험을 통제 환경에서 시연"],rf:[["Ettercap","https://www.ettercap-project.org/"]]},
  mitmproxy:{ov:"HTTP/S 가로채기 프록시. 스크립팅으로 트래픽을 변조한다.",tc:[{t:"API 가로채기",s:"mitmproxy --mode transparent 로 모바일 SaMD의 API 호출 관찰·수정"},{t:"핀닝 검증",s:"인증서 신뢰 후 트래픽이 보이는지로 TLS 핀닝 적용 여부 확인"}],cs:["모바일 SaMD의 API 인증·인가·핀닝 평가"],rf:[["mitmproxy Docs","https://docs.mitmproxy.org/"]]},
  responder:{ov:"LLMNR/NBT-NS/mDNS 포이즈닝으로 자격증명을 수집한다.",tc:[{t:"이름 해석 포이즈닝",s:"responder -I <if> 로 격리망에서 인증 흐름의 약점·해시 수집 확인"}],cs:["병원 내부망 SaMD 서버의 인증 흐름 약점 검증(격리망 한정)"],rf:[["Responder","https://github.com/lgandx/Responder"]]},
  snmpwalk:{ov:"SNMP로 장비 설정·자산 정보를 열거한다.",tc:[{t:"커뮤니티 문자열 열거",s:"snmpwalk -v2c -c public <dev> 로 기본 커뮤니티 노출·구성 정보 확인"}],cs:["관리 인터페이스가 열린 의료기기의 구성 노출 점검"],rf:[["Net-SNMP","http://www.net-snmp.org/docs/man/"]]},
  enum4linux:{ov:"SMB/Windows 공유·사용자·정책을 열거한다.",tc:[{t:"SMB 전수 열거",s:"enum4linux -a <host> 로 공유·계정·정책 노출 확인"}],cs:["Windows 기반 PACS/워크스테이션의 공유·계정 노출 점검"],rf:[["enum4linux","https://github.com/CiscoCXSecurity/enum4linux"]]},
  smbclient:{ov:"SMB 공유 접근·파일 전송 클라이언트.",tc:[{t:"익명 접근 확인",s:"smbclient -L //<host> -N 으로 비인증 공유 열거"}],cs:["영상·리포트 공유의 익명 접근 가능성 확인"],rf:[["Samba","https://www.samba.org/samba/docs/"]]},
  burpsuite:{ov:"웹/API 테스트 통합 플랫폼. 프록시·스캐너·리피터·인트루더를 제공한다.",tc:[{t:"인증·인가 테스트",s:"세션 토큰 조작·IDOR 테스트로 권한 상승·데이터 접근 결함 확인"},{t:"입력 검증",s:"Repeater/Intruder로 인젝션·검증 우회 페이로드 시험"}],cs:["SaMD 웹/API의 인증·인가·입력검증 결함을 체계적으로 평가"],rf:[["Burp Docs","https://portswigger.net/burp/documentation"]]},
  sqlmap:{ov:"SQL 인젝션을 자동 탐지·추출한다.",tc:[{t:"인젝션 탐지",s:"sqlmap -u '<url>?id=1' --batch 로 취약 파라미터 식별"},{t:"데이터 추출 PoC",s:"--dump 으로 (승인된 범위에서) 노출 가능 데이터 입증"}],cs:["PHI 저장 백엔드에 대한 인젝션으로 데이터 노출 위험 입증"],rf:[["sqlmap Wiki","https://github.com/sqlmapproject/sqlmap/wiki"]]},
  nikto:{ov:"웹 서버 설정 오류·위험 파일을 스캔한다.",tc:[{t:"서버 설정 스캔",s:"nikto -h https://app 로 노출 관리 페이지·구버전·위험 파일 탐지"}],cs:["SaMD 서버의 노출 관리 인터페이스·구버전 식별"],rf:[["Nikto","https://github.com/sullo/nikto"]]},
  ffuf:{ov:"초고속 웹 퍼저. 디렉터리·파라미터·vhost를 탐색한다.",tc:[{t:"숨은 경로 탐색",s:"ffuf -u https://app/FUZZ -w <wordlist> 로 문서화되지 않은 엔드포인트 발견"}],cs:["숨은 API 엔드포인트·관리 경로 발견"],rf:[["ffuf","https://github.com/ffuf/ffuf"]]},
  gobuster:{ov:"디렉터리·DNS·vhost 브루트포스 도구.",tc:[{t:"디렉터리 브루트포스",s:"gobuster dir -u https://app -w <list> 로 숨은 리소스 열거"}],cs:["문서화되지 않은 SaMD 리소스 열거"],rf:[["gobuster","https://github.com/OJ/gobuster"]]},
  dirb:{ov:"웹 콘텐츠 디렉터리 스캐너(경량).",tc:[{t:"기본 디렉터리 스캔",s:"dirb https://app 로 기본 워드리스트 기반 탐색"}],cs:["경량 디렉터리 탐색 대안"],rf:[["dirb","https://www.kali.org/tools/dirb/"]]},
  wpscan:{ov:"WordPress 취약점·플러그인·사용자 스캐너.",tc:[{t:"CMS 취약점 스캔",s:"wpscan --url https://portal 로 플러그인·사용자·취약점 열거"}],cs:["환자 포털 등 CMS 기반 SaMD 자산 평가"],rf:[["WPScan","https://github.com/wpscanteam/wpscan"]]},
  sslscan:{ov:"TLS 구성·암호군·인증서를 점검한다.",tc:[{t:"TLS 구성 점검",s:"sslscan <host>:443 으로 약한 암호군·프로토콜·만료 인증서 식별"}],cs:["PHI 전송 구간의 약한 TLS·만료 인증서 식별"],rf:[["sslscan","https://github.com/rbsec/sslscan"]]},
  sslyze:{ov:"정밀 TLS 분석기. 취약점·설정을 자동 평가한다.",tc:[{t:"전송 암호화 평가",s:"sslyze <host>:443 으로 준수 여부·취약 설정 자동 리포트"}],cs:["전송 암호화 준수(FDA·HIPAA) 근거 자료 생성"],rf:[["SSLyze","https://github.com/nabla-c0d3/sslyze"]]},
  "aircrack-ng":{ov:"Wi-Fi 모니터링·캡처·WPA 핸드셰이크 크래킹 스위트.",tc:[{t:"무선 모니터링",s:"airodump-ng <mon> 로 주변 AP·클라이언트·채널 수집"},{t:"핸드셰이크 크래킹",s:"캡처한 핸드셰이크를 aircrack-ng로 약한 PSK 검증"}],cs:["Wi-Fi 연결 의료기기의 무선 보안·네트워크 분리 검증"],rf:[["Aircrack-ng","https://www.aircrack-ng.org/documentation.html"]]},
  kismet:{ov:"무선 탐지·스니핑·디바이스 트래킹(Wi-Fi/BT/SDR).",tc:[{t:"무선 자산 탐지",s:"kismet -c <mon> 으로 테스트 공간 내 미등록 무선 기기 발견"}],cs:["테스트 공간 내 미등록 무선 의료기기 식별"],rf:[["Kismet Docs","https://www.kismetwireless.net/docs/"]]},
  reaver:{ov:"WPS 핀 브루트포스로 Wi-Fi 키를 복구한다.",tc:[{t:"WPS 공격",s:"reaver -i <mon> -b <bssid> 로 WPS 활성 AP의 약점 입증"}],cs:["WPS가 켜진 기기 게이트웨이의 약점 입증"],rf:[["reaver","https://github.com/t6x/reaver-wps-fork-t6x"]]},
  bluetoothctl:{ov:"BlueZ 제어 CLI. BLE 장치 스캔·페어링·연결을 수행한다.",tc:[{t:"BLE 장치 스캔",s:"bluetoothctl scan on 으로 광고 패킷·장치 식별"},{t:"페어링 보안 관찰",s:"페어링 시도로 Just Works 등 약한 페어링 모드 확인"}],cs:["BLE 웨어러블/이식형의 광고·페어링 보안 관찰"],rf:[["BlueZ","http://www.bluez.org/"]]},
  gatttool:{ov:"BLE GATT 서비스·특성을 열거하고 읽기/쓰기한다.",tc:[{t:"GATT 열거",s:"gatttool -b <MAC> -I 에서 characteristics 로 서비스·특성 나열"},{t:"비인증 쓰기 시험",s:"인증 없이 특성에 쓰기 시도로 명령 주입 가능성 검증"}],cs:["BLE 기기의 인증 없는 특성 쓰기(명령 주입) 검증"],rf:[["BlueZ","http://www.bluez.org/"]]},
  hcitool:{ov:"저수준 Bluetooth 조회·장치 탐색 도구.",tc:[{t:"BLE 스캔",s:"hcitool lescan 으로 BLE 기기·MAC 수집"}],cs:["BLE 기기 식별·MAC 수집(프라이버시·주소 랜덤화 점검)"],rf:[["BlueZ","http://www.bluez.org/"]]},
  spooftooph:{ov:"Bluetooth 장치 정보를 스푸핑한다.",tc:[{t:"장치 위조",s:"spooftooph -i hci0 -a <MAC> 로 신뢰·페어링 모델의 위조 내성 평가"}],cs:["BLE 신뢰·페어링 모델의 위조 내성 평가"],rf:[["spooftooph","https://www.kali.org/tools/spooftooph/"]]},
  binwalk:{ov:"펌웨어 이미지 분석·파일시스템 추출·엔트로피 분석 도구.",tc:[{t:"펌웨어 추출",s:"binwalk -eM firmware.bin 으로 내장 파일시스템·이미지 재귀 추출"},{t:"하드코딩 비밀 탐색",s:"추출 루트FS에서 키·인증서·자격증명 검색"}],cs:["SiMD 펌웨어에서 파일시스템·하드코딩 비밀 추출"],rf:[["binwalk","https://github.com/ReFirmLabs/binwalk"]]},
  radare2:{ov:"역공학 프레임워크. 디스어셈블·디버그·패치를 지원한다.",tc:[{t:"바이너리 분석",s:"r2 -A firmware.elf 에서 함수·문자열·인증 경로 분석"},{t:"인증 우회 탐색",s:"분기·검증 루틴을 분석해 우회 가능성 식별"}],cs:["펌웨어 바이너리의 로직·인증 우회 경로 분석"],rf:[["radare2 book","https://book.rada.re/"]]},
  sasquatch:{ov:"변형 SquashFS 추출 유틸(binwalk 보조).",tc:[{t:"비표준 루트FS 복원",s:"sasquatch rootfs.squashfs 로 변형 압축 파일시스템 복원"}],cs:["비표준 압축 펌웨어 루트FS 복원"],rf:[["sasquatch","https://github.com/devttys0/sasquatch"]]},
  flashrom:{ov:"SPI/플래시 칩 읽기·쓰기(하드웨어 프로그래머 연동).",tc:[{t:"펌웨어 덤프",s:"flashrom -p <prog> -r dump.bin 으로 물리 접근 시 펌웨어 직접 추출"}],cs:["물리 접근 시 SiMD 플래시에서 펌웨어 직접 덤프"],rf:[["flashrom","https://www.flashrom.org/"]]},
  objdump:{ov:"바이너리 디스어셈블·섹션 분석(binutils).",tc:[{t:"디스어셈블",s:"objdump -d firmware.elf 로 함수·심볼 신속 검토"}],cs:["임베디드 바이너리의 함수·심볼 신속 검토"],rf:[["GNU binutils","https://sourceware.org/binutils/docs/"]]},
  strings:{ov:"바이너리 내 출력 가능 문자열을 추출한다.",tc:[{t:"문자열 추출",s:"strings -n 8 firmware.bin 으로 자격증명·엔드포인트·디버그 문자열 탐색"}],cs:["펌웨어의 자격증명·엔드포인트·디버그 문자열 발견"],rf:[["GNU binutils","https://sourceware.org/binutils/docs/"]]},
  metasploit:{ov:"익스플로잇·페이로드·포스트 모듈 프레임워크(msfconsole).",tc:[{t:"통제된 PoC",s:"확인된 취약점에 대해 모듈로 영향(안전 영향 포함)을 통제 환경에서 입증"}],cs:["확인된 취약점의 실제 영향을 통제된 PoC로 입증"],rf:[["Metasploit Docs","https://docs.metasploit.com/"]]},
  hydra:{ov:"네트워크 로그인 브루트포스(SSH/HTTP/RDP 등).",tc:[{t:"기본 자격증명 검증",s:"hydra -L u.txt -P p.txt <svc>://<host> 로 약한·기본 자격증명 확인"}],cs:["관리 인터페이스의 약한·기본 자격증명 검증"],rf:[["THC-Hydra","https://github.com/vanhauser-thc/thc-hydra"]]},
  john:{ov:"John the Ripper. 해시 크래킹·규칙 기반 공격.",tc:[{t:"해시 강도 평가",s:"john --wordlist=<wl> hashes 로 추출 해시의 크래킹 난이도 측정"}],cs:["펌웨어/DB에서 추출한 해시의 강도 평가"],rf:[["John the Ripper","https://www.openwall.com/john/doc/"]]},
  hashcat:{ov:"GPU 가속 해시 크래킹 도구.",tc:[{t:"대량 해시 크래킹",s:"hashcat -m <mode> -a 0 hashes <wl> 로 알고리즘별 현실적 크래킹 비용 산정"}],cs:["대량 해시·강한 알고리즘의 현실적 크래킹 비용 산정"],rf:[["hashcat wiki","https://hashcat.net/wiki/"]]},
  dcmtk:{ov:"DICOM 툴킷(storescu/findscu/echoscu). DICOM 노드와 직접 통신한다.",tc:[{t:"연결·인증 확인",s:"echoscu <host> 104 로 C-ECHO 연결·비인증 수락 여부 확인"},{t:"정보 열거",s:"findscu 로 C-FIND 질의, 비인증 환자정보 조회 가능성 점검"},{t:"C-STORE 남용",s:"storescu 로 임의 객체 전송이 허용되는지 검증"}],cs:["DICOM 서비스의 인증 부재·C-STORE 남용·정보 열거 테스트"],rf:[["DCMTK","https://dicom.offis.de/dcmtk.php.en"]]},
  mosquitto:{ov:"MQTT 브로커·클라이언트(pub/sub). IoT 메시징 테스트에 쓰인다.",tc:[{t:"무단 구독",s:"mosquitto_sub -h <broker> -t '#' -v 로 전체 토픽 무단 구독 가능성 확인"},{t:"무단 발행",s:"mosquitto_pub 로 제어 토픽에 메시지 발행이 허용되는지 검증"}],cs:["원격 모니터링 SiMD의 MQTT 토픽 무단 구독·발행 검증"],rf:[["Mosquitto","https://mosquitto.org/documentation/"]]},
  frida:{ov:"동적 계측 툴킷. 런타임 후킹·인증서 핀닝 우회를 지원한다.",tc:[{t:"프로세스 탐색",s:"frida-ps -U 로 대상 기기 프로세스 확인 후 후킹 대상 선정"},{t:"핀닝 우회",s:"TLS 검증 함수를 후킹해 트래픽 관찰 가능 여부 확인"}],cs:["모바일 SaMD의 핀닝 우회·런타임 로직 분석"],rf:[["Frida Docs","https://frida.re/docs/home/"]]},
  apktool:{ov:"안드로이드 APK 디컴파일·리빌드 도구.",tc:[{t:"정적 분석",s:"apktool d app.apk -o out/ 로 리소스·스몰리 코드·설정 추출"}],cs:["모바일 SaMD의 리소스·스몰리 코드·비밀 정적 분석"],rf:[["Apktool","https://apktool.org/"]]},
  jadx:{ov:"Dalvik 바이트코드를 Java로 디컴파일한다.",tc:[{t:"Java 디컴파일",s:"jadx -d out/ app.apk 로 가독성 높은 Java 소스 복원·검토"}],cs:["모바일 SaMD 앱 로직·하드코딩 키 검토"],rf:[["jadx","https://github.com/skylot/jadx"]]},
  ghidra:{ov:"NSA 역공학 스위트. 멀티아키 디컴파일을 지원한다.",tc:[{t:"펌웨어 디컴파일",s:"프로젝트에 펌웨어 로드 후 디컴파일러로 로직·취약점 식별"}],cs:["SiMD 펌웨어의 심층 역공학·취약점 식별"],rf:[["Ghidra","https://ghidra-sre.org/"]]},
  "can-utils":{ov:"CAN 버스 송수신·덤프(candump/cansend).",tc:[{t:"버스 트래픽 관찰",s:"candump can0 로 CAN 메시지 관찰·ID 매핑"},{t:"메시지 주입",s:"cansend 로 (격리 벤치에서) 제어 메시지 영향 검증"}],cs:["CAN 기반 의료 플랫폼의 버스 메시지 관찰·주입"],rf:[["can-utils","https://github.com/linux-can/can-utils"]]},
  volatility3:{ov:"메모리 포렌식 프레임워크(vol).",tc:[{t:"메모리 분석",s:"vol -f dump.raw windows.info 등으로 프로세스·아티팩트 분석"}],cs:["사후시장 사고 대응·메모리 내 PHI 잔존 확인"],rf:[["Volatility 3","https://volatility3.readthedocs.io/"]]},
  objection:{ov:"Frida 기반 런타임 모바일 탐색·핀닝 우회 자동화.",tc:[{t:"런타임 탐색",s:"objection -g <pkg> explore 로 로컬 저장소·메서드 후킹 신속 점검"}],cs:["모바일 SaMD의 핀닝 우회·로컬 저장소 점검"],rf:[["objection","https://github.com/sensepost/objection"]]},
  gnuradio:{ov:"SDR 신호처리 프레임워크. 복조·디코딩 플로우를 구성한다.",tc:[{t:"복조 플로우 구성",s:"gnuradio-companion 에서 전용 무선 신호의 복조·디코딩 그래프 작성"}],cs:["전용 RF로 통신하는 SiMD(텔레메트리·이식형)의 변조 방식 역설계"],rf:[["GNU Radio","https://www.gnuradio.org/"]]},
  gqrx:{ov:"SDR 수신·스펙트럼 분석 GUI.",tc:[{t:"대역 식별",s:"gqrx 로 기기 RF 방출 대역·채널 관찰"}],cs:["의료기기의 RF 방출 대역·채널 식별(정찰)"],rf:[["Gqrx","https://gqrx.dk/"]]},
  hackrf:{ov:"1MHz–6GHz SDR 송수신 하드웨어 도구모음.",tc:[{t:"신호 캡처·재전송",s:"hackrf_transfer 로 격리 벤치에서 전용 RF 신호 캡처·재전송 내성 검증"}],cs:["격리 벤치에서 전용 RF 신호 캡처·재전송(replay) 내성 검증"],rf:[["HackRF Docs","https://hackrf.readthedocs.io/"]]},
  "multimon-ng":{ov:"POCSAG·FLEX 등 디지털 모드 디코더.",tc:[{t:"디지털 모드 디코딩",s:"multimon-ng -a POCSAG1200 - 로 평문 텔레메트리/호출 정보 디코딩"}],cs:["병원 호출(pager) 등 평문 텔레메트리의 정보 노출 확인"],rf:[["multimon-ng","https://github.com/EliasOenal/multimon-ng"]]},
  inspectrum:{ov:"캡처된 신호의 시각적 분석·심볼 추출 도구.",tc:[{t:"신호 역설계",s:"inspectrum capture.cf32 로 패킷 구조·심볼·타이밍 분석"}],cs:["전용 RF의 패킷 구조·타이밍 역설계"],rf:[["inspectrum","https://github.com/miek/inspectrum"]]},
  rfcat:{ov:"서브-GHz(ISM) RF 송수신 제어(TI 칩셋).",tc:[{t:"ISM 명령 주입",s:"rfcat 대화형에서 ISM 대역 전용 프로토콜의 명령 주입·재전송 시험"}],cs:["ISM 대역 전용 프로토콜의 명령 주입·재전송 테스트"],rf:[["rfcat","https://github.com/atlas0fd00m/rfcat"]]},
  proxmark3:{ov:"RFID/NFC 분석·복제·에뮬레이션 플랫폼.",tc:[{t:"태그 복제 내성",s:"proxmark3 로 RFID/NFC 태그 읽기·복제·에뮬레이션 내성 검증"}],cs:["RFID 기반 접근제어·이식형 식별 태그의 복제·변조 내성 검증"],rf:[["Proxmark3","https://github.com/RfidResearchGroup/proxmark3"]]},
  openocd:{ov:"JTAG/SWD 온칩 디버깅·플래시 접근 도구.",tc:[{t:"디버그 포트 접근",s:"openocd -f <board>.cfg 로 JTAG/SWD 연결, 플래시 덤프·메모리 접근 가능성 검증"}],cs:["SiMD의 디버그 포트를 통한 펌웨어 덤프·메모리 접근(보호 여부 검증)"],rf:[["OpenOCD","https://openocd.org/doc/html/index.html"]]},
  minicom:{ov:"시리얼 터미널. UART 콘솔에 접근한다.",tc:[{t:"UART 콘솔 접근",s:"minicom -D /dev/ttyUSB0 -b 115200 로 비인증 셸·부트로그 노출 확인"}],cs:["의료기기 UART 콘솔의 인증 없는 셸·부트로그 노출 확인"],rf:[["minicom","https://www.kali.org/tools/minicom/"]]},
  "qemu-user":{ov:"크로스아키 사용자모드 에뮬레이션(ARM/MIPS 등).",tc:[{t:"격리 실행 분석",s:"qemu-arm ./fw-binary 로 추출 바이너리를 격리 환경에서 안전하게 실행·분석"}],cs:["추출한 SiMD 펌웨어 바이너리를 격리 환경에서 안전하게 실행·분석"],rf:[["QEMU Docs","https://www.qemu.org/docs/master/"]]},
  cutter:{ov:"Rizin 기반 역공학 GUI(rz-ghidra 디컴파일러 포함).",tc:[{t:"펌웨어 디컴파일",s:"cutter firmware.elf 로 디컴파일·그래프 분석(Ghidra 대안)"}],cs:["Ghidra 대안으로 펌웨어 디컴파일·그래프 분석"],rf:[["Cutter","https://cutter.re/"]]},
  ubertooth:{ov:"BLE 패킷 스니핑 하드웨어 도구모음.",tc:[{t:"BLE 스니핑",s:"ubertooth-btle 로 앱-기기 간 BLE 트래픽 캡처, 평문·약한 페어링 식별"}],cs:["앱-기기 간 BLE 트래픽 캡처로 평문·약한 페어링 식별"],rf:[["Ubertooth Wiki","https://github.com/greatscottgadgets/ubertooth/wiki"]]},
  crackle:{ov:"BLE 레거시 페어링(LE Legacy) 암호를 크랙한다.",tc:[{t:"페어링 복호화",s:"crackle -i ble.pcap 로 약한 LE Legacy 페어링 캡처의 복호화 가능성 입증"}],cs:["BLE 웨어러블/이식형의 약한 페어링으로 인한 트래픽 복호화 입증"],rf:[["crackle","https://github.com/mikeryan/crackle"]]},
  btscanner:{ov:"Bluetooth 장치 탐색·정보 수집 도구.",tc:[{t:"BT 장치 탐색",s:"btscanner 로 주변 BLE 의료기기 식별·정보 수집"}],cs:["테스트 공간의 BLE 의료기기 식별·정보 노출 점검"],rf:[["btscanner","https://www.kali.org/tools/btscanner/"]]},
  dex2jar:{ov:"Android dex를 jar로 변환한다(정적 분석 전처리).",tc:[{t:"dex→jar 변환",s:"d2j-dex2jar app.apk 로 jar 생성 후 jd-gui 등으로 Java 검토"}],cs:["모바일 SaMD를 Java 수준으로 검토하기 위한 전처리"],rf:[["dex2jar","https://github.com/pxb1988/dex2jar"]]},
  "jd-gui":{ov:"Java 바이트코드 디컴파일 GUI.",tc:[{t:"Java 디컴파일 검토",s:"jd-gui app-dex2jar.jar 로 로직·하드코딩 비밀을 가독성 있게 검토"}],cs:["모바일 SaMD 로직·하드코딩 비밀의 가독성 높은 검토"],rf:[["JD-GUI","https://github.com/java-decompiler/jd-gui"]]},
  syft:{ov:"파일시스템·컨테이너 이미지에서 SPDX/CycloneDX SBOM을 생성한다. FDA 시판 전 제출의 기계판독 SBOM 요구에 대응.",tc:[{t:"SBOM 생성",s:"syft dir:./firmware -o cyclonedx-json=sbom.json 으로 구성요소·버전 목록화"},{t:"포맷 변환",s:"-o spdx-json 등으로 제출 포맷에 맞춰 출력"}],cs:["SaMD/SiMD 소프트웨어 구성요소 인벤토리를 기계판독 SBOM으로 산출","trivy/grype와 연계해 SBOM 취약점 대조"],rf:[["Syft","https://github.com/anchore/syft"]]},
  trivy:{ov:"SBOM 생성과 알려진 취약점(CVE) 스캔을 함께 수행한다. 파일시스템·이미지·SBOM·IaC 대상.",tc:[{t:"파일시스템 취약점 스캔",s:"trivy fs ./app 로 의존성·OS 패키지의 알려진 취약점 탐지"},{t:"SBOM 생성",s:"trivy fs --format cyclonedx -o sbom.json ./app"},{t:"SBOM 대조",s:"trivy sbom sbom.json 으로 기존 SBOM의 취약점 점검"}],cs:["SBOM 구성요소의 알려진 취약점 대조(사후시장 취약점 관리 근거)","컨테이너 기반 SaMD 클라우드 이미지 취약점 평가"],rf:[["Trivy","https://trivy.dev/"]]},
  cyclonedx:{ov:"CycloneDX 표준 포맷 SBOM을 Python 의존성에서 생성한다.",tc:[{t:"요구사항 기반 SBOM",s:"cyclonedx-py requirements -i requirements.txt -o sbom.json"},{t:"환경 기반 SBOM",s:"cyclonedx-py environment 로 설치 환경의 구성요소 목록화"}],cs:["Python 기반 SaMD 백엔드의 표준 포맷 SBOM 산출"],rf:[["CycloneDX Python","https://github.com/CycloneDX/cyclonedx-python"]]},
  "pip-audit":{ov:"Python 의존성의 알려진 취약점을 PyPA Advisory DB로 감사한다.",tc:[{t:"요구사항 감사",s:"pip-audit -r requirements.txt 로 취약 패키지·수정 버전 식별"},{t:"SBOM 출력",s:"--format cyclonedx-json 으로 결과를 SBOM과 함께 제출"}],cs:["SaMD 백엔드 의존성의 취약 패키지 식별·패치 계획 수립"],rf:[["pip-audit","https://github.com/pypa/pip-audit"]]}
};
